version: "3.5"

services:
  app1:
    build: app1
    container_name: app1
    image: app1
    expose:
      - "10011"
    restart: unless-stopped
    # environment:
    #   VIRTUAL_HOST: www.some-domain.org, some-domain.org
    #   LETSENCRYPT_HOST: www.some-domain.org, some-domain.org
    #   LETSENCRYPT_EMAIL: admin@some-domain.org
    #   LETSENCRYPT_TEST: "true"
  app2:
    build: app2
    container_name: app2
    image: app2
    expose:
      - "10012"
    restart: unless-stopped
    # environment:
    #   VIRTUAL_HOST: www.some-domain.org, some-domain.org
    #   LETSENCRYPT_HOST: www.some-domain.org, some-domain.org
    #   LETSENCRYPT_EMAIL: admin@some-domain.org
    #   LETSENCRYPT_TEST: "true"
  app3:
    build: app3
    container_name: app3
    image: app3
    expose:
      - "10013"
    restart: unless-stopped
    # environment:
    #   VIRTUAL_HOST: www.some-domain.org, some-domain.org
    #   LETSENCRYPT_HOST: www.some-domain.org, some-domain.org
    #   LETSENCRYPT_EMAIL: admin@some-domain.org
    #   LETSENCRYPT_TEST: "true"

# networks:
#   default:
#     external:
#       name: webproxy
