version: "2"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  app1:
    container_name: app1-ap
    image: app1-ap
    networks:
      - proxy-tier
    environment:
      VIRTUAL_HOST: "www.adolfo-peixinho.eu.org,adolfo-peixinho.eu.org"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 80
    restart: always
