version: "3.2"

services:
  app1:
    build: app1
    container_name: app1
    image: app1
    ports:
    expose:
      - "10001"
    restart: unless-stopped
    # environment:
    #   VIRTUAL_HOST: www.adolfo-peixinho.eu.org, adolfo-peixinho.eu.org
    #   LETSENCRYPT_HOST: www.adolfo-peixinho.eu.org, adolfo-peixinho.eu.org
    #   LETSENCRYPT_EMAIL: admin@vps.domain
  app2:
    build: app2
    container_name: app2
    image: app2
    expose:
      - "10002"
    restart: unless-stopped
    # environment:
    #   VIRTUAL_HOST: www.peixe.eu.org, peixe.eu.org
    #   LETSENCRYPT_HOST: www.peixe.eu.org, peixe.eu.org
    #   LETSENCRYPT_EMAIL: admin@vps.domain
  app3:
    build: app3
    container_name: app3
    image: app3
    expose:
      - "10003"
    restart: unless-stopped
    # environment:
    #   VIRTUAL_HOST: www.hoho.eu.org, hoho.eu.org
    #   LETSENCRYPT_HOST: www.hoho.eu.org, hoho.eu.org
    #   LETSENCRYPT_EMAIL: admin@vps.domain

networks:
  default:
    external:
      name: webproxy
