version: "3.2"

services:
  proxy:
    image: zzrot/alpine-caddy
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy-certs:/root/.caddy
    networks:
      - proxy-tier
    restart: always

  # example-server:
  #   image: zzrot/alpine-caddy
  #   expose:
  #     - 80
  #   volumes:
  #     - ./public:/var/www/html
  #   networks:
  #     - proxy-tier
  app1:
    build: app1
    container_name: app1-ap
    image: app1-ap
    networks:
      - proxy-tier
    expose:
      - "10001"
    restart: always

  app2:
    build: app2
    container_name: app2-ap
    image: app2-ap
    networks:
      - proxy-tier
    expose:
      - "10002"
    restart: always

networks:
  proxy-tier:
    external: true
