version: '3'

services:
  app1:
    container_name: app1-ap
    image: app1-ap
    networks:
      - proxy-tier
    expose:
      - "80"
      - "443"  
    environment:
      VIRTUAL_HOST: adolfo-peixinho.eu.org, www.adolfo-peixinho.eu.org
      LETSENCRYPT_HOST: adolfo-peixinho.eu.org, www.adolfo-peixinho.eu.org
      LETSENCRYPT_EMAIL: youradminrules@fu.org
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
    restart: always    

networks:
  proxy-tier:
    external: true

# environment:
#   VIRTUAL_HOST: domain.com, www.domain.com
#   VIRTUAL_PROTO: https
  # VIRTUAL_PORT: 443
  # LETSENCRYPT_HOST: domain.com, www.domain.com
  # LETSENCRYPT_EMAIL: your_email@domain.com    
