version: '3'

services:
  app1:
    container_name: app1-ap
    image: app1-ap
    networks:
      - proxy-tier
    environment:
      VIRTUAL_HOST: adolfo-peixinho.eu.org, www.adolfo-peixinho.eu.org
      VIRTUAL_PROTO: https
    restart: always

networks:
  proxy-tier:
    external:

# environment:
#   VIRTUAL_HOST: domain.com, www.domain.com
#   VIRTUAL_PROTO: https
  # VIRTUAL_PORT: 443
  # LETSENCRYPT_HOST: domain.com, www.domain.com
  # LETSENCRYPT_EMAIL: your_email@domain.com    
