version: "3.6"
services:
  app1:
    image: app1
    networks:
      - webgateway
    deploy:
      # replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.3"
          memory: 60M
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"  
        - "traefik.frontend.rule=Host:hoho.eu.org,www.hoho.eu.org;PathStrip:/app1/"
        - "traefik.backend=app1"
        - "traefik.backend.loadbalancer.method=drr"
        - "traefik.port=10011"
        - "traefik.docker.network=webgateway"

networks:
  webgateway:
    driver: overlay
    external: true
