FROM node:8-alpine

ENV NODE_PATH=/usr/local/lib/node_modules

RUN addgroup -S app && adduser -S -g app app && \
    apk update && apk upgrade && \
    apk add --no-cache build-base && \
    npm i -g pm2 && \
    rm -f /var/cache/apk/*

WORKDIR /home/app

COPY processes.json app1.js /home/app/

USER app

RUN npm i pm2 express 

RUN chown -R app:app /home/app




EXPOSE 10001

# CMD ["pm2-docker", "start","processes.json"]
CMD ["tail","-f", "/dev/null"]
