FROM node:carbon-alpine

# Setup environment variables. 
# If using one liner breakpoint '\' you can't use previously defined
# variables in posterior variables. Just define ENV per line
ENV NODE_ENV=production
# ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
# ENV PATH=${PATH}:${NPM_CONFIG_PREFIX}/bin

# Following best practices at:
# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md

# add a group and user for our app, for a system user or group
# add '-S' to addgroup or adduser commands
#RUN addgroup -S app && adduser -S -g app app && \
RUN apk update && apk upgrade && \
    apk add --no-cache build-base && \
    rm -f /var/cache/apk/*

COPY pm2-conf.json app2.js public /home/node/

RUN chown -R node:node /home/node

USER node

WORKDIR /home/node

RUN npm i -g pm2 --no-save --no-package-lock --ignore-scripts && \
    npm i express helmet --no-save --no-package-lock --ignore-scripts 

EXPOSE 10012

CMD ["pm2-docker", "start", "pm2-conf.json"]
# CMD ["tail","-f", "/dev/null"]
